# 1st attempt
image: google/cloud-sdk:alpine

deploy_production:
  stage: deploy
  environment: Production
  only:
  - main
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud auth list
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml

# deploy_staging:
#   stage: deploy
#   environment: Staging
#   only:
#   - staging
#   script:
#   - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
#   - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
#   - gcloud --quiet --project $PROJECT_ID app deploy staging-app.yaml

after_script:
- rm /tmp/$CI_PIPELINE_ID.json